### ISSUE TITLE
Add network tracking tests

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb_benchmarks#5]
Using structure of https://github.com/lbl-cbg/nwb-cloud-io/pull/3

In the testing suite, this would be implemented (in at least one way) as

```
def track_network_<other case specifiers>:
    with network_tracking as network_results:
        # Run the operation (presumably streaming)
    return network_results
```

Following the instructions for [generic tracking on ASV](https://asv.readthedocs.io/en/stable/writing_benchmarks.html#tracking-generic) - note the output must be numeric? Haven't tested the limits of it yet

I will also say that this does mean there might be some duplication in the tests per element that we want to track. Say we want to track the time, memory, and network traffic of a single read operation from a single file on DANDI; that would technically end up as 3 separate runs of the same operation. Some overhead could be reduced by combining them all in the same class for a common setup, but the actual slicing and range request would have to be repeated each time for each numeric value we want to track; I think this philosophy is done to minimize the chance that a tracking activity might itself interfere with other measurements

**Comment by oruebel** [comment]
> that would technically end up as 3 separate runs of the same operation

Having separate runs for the different metrics makes sense since network and memory profiling tend to affect the other metrics. However, it would be useful to have the code that is being evaluated be implemented in a central place.

 

> In the testing suite, this would be implemented (in at least one way) as

Does the test itself need to return the metric or can the metric be computed in the tearDown?

> note the output must be numeric?

Does it allow multiple metrics? For network we would want to track e.g: 1) number of packets, 2) amount of data, 3) download speed, 4) latency etc. , which would all be computed in a single test run.

**Comment by oruebel** [comment]
For the network tests we'll need to to updated the environment to :

- install tshark https://tshark.dev/setup/install/  as a command-line tool. I don't think tshark can be installed via pip/conda .
- install psutils
- At least on macOS and AIX, we'll need to run the network tests with root/sudo permissions, which are needed for `psutil.net_connections()` to work https://psutil.readthedocs.io/en/latest/#psutil.net_connections

**Comment by CodyCBakerPhD** [comment]
> Does the test itself need to return the metric or can the metric be computed in the tearDown?

The `track_*` function is what needs to `return` the value(s) being tracked

> Does it allow multiple metrics? For network we would want to track e.g: 1) number of packets, 2) amount of data, 3) download speed, 4) latency etc. , which would all be computed in a single test run.

That's a big question, I'll test out some stuff and find out for sure

I suppose word case scenario you could always track all 4 and serialize them, then de-serialize when reading the results (assuming it allows string values not just numeric)

> However, it would be useful to have the code that is being evaluated be implemented in a central place.

Yeah, there are a couple designs that might allow this, all comes down to how you structure the classes and their methods/attributes w.r.t. the code block and required setup

**Comment by oruebel** [comment]
> The `track_*` function is what needs to `return` the value(s) being tracked

Makes sense. Maybe I'll make a decorator to post-process the network captures and create the stats so that I don't have to do it in every function. 

> That's a big question, I'll test out some stuff and find out for sure

Thanks! At first glance, it seems like it wants one metric with a specific unit for each test. Worst case, I can make separate classes for each metric, but it would be nice to capture them all at the same time, since these metrics vary between runs (e.g., the number of packets depends on how many errors occur during data transfer). I guess I could in principle cache the results and have some tests that just load the cached metrics to separate them from ASV, but that seems hacky.

**Comment by oruebel** [comment]
> I guess I could in principle cache the results and have some tests that just load the cached metrics to separate them from ASV, but that seems hacky.

Actually, I think that could work. ASV does have a separate `setup_cache` method and according to the docs  _A separate cache is used for each environment and each commit of the project being tested and is thrown out between benchmark runs._  If that is the case, then I think I could execute all the profiling in the `setup_cache` method, save the metrics in the cache, and then the test functions would retrieve the corresponding metric from the cache and return it. https://asv.readthedocs.io/en/stable/writing_benchmarks.html#setup-and-teardown

**Comment by CodyCBakerPhD** [comment]
Yes, that sounds OK to me
